"This code generates the OTP of google authenticator"

import pyotp
import qrcode
t=pyotp.TOTP('QEZBVABZBS3DMNLF2I45DYP2HQ') # this is the string generated by google authenticator server
auth_str=t.provisioning_uri(name='abc.def@ghi.com',issuer_name='ASDF')
print(auth_str)
img=qrcode.make(auth_str)
display(img)
print(t.now())   # this t.now() generated the OTP
